### ISSUE TITLE
example with extract text plugin

### ISSUE THREAD

**Issue by applemate** [ksrb/babel-plugin-react-css-modules-test#1]
Hi, do you have an example of the loader below with extract text plugin?

```js
{
	test: /\.scss$/,
	loaders: [
		'style?sourceMap',
		'css?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]',
		'resolve-url',
		'sass?sourceMap'
	]
}
```

**Comment by ksrb** [comment]
There's a example in https://github.com/gajus/react-css-modules#module-bundler. 

You're going to need to do a little scrolling as there's no anchor I could link to directly.
